AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
#Need to upload zip to S3 first 
  InputTopic:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: 'd9-findings'
      TopicName: 'd9-findings'
  InputTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: D9DeliveryPolicy
        Version: '2012-10-17'
        Statement:
        - Sid: D9DeliveryPolicy
          Effect: Allow
          Principal:
            AWS: 'arn:aws:iam::634729597623:root'
          Action: sns:Publish
          Resource: !Ref InputTopic
      Topics:
      - !Ref InputTopic

  OutputTopic:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: 'remediationOutput'
      TopicName: 'remediationOutput'
  RemediationFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: dome9AutoRemediations
      Description: 'Auto-remediation actions from Dome9 events'
      CodeUri: ./remediation-function.zip
      Runtime: python3.6
      Timeout: 8
      Handler: index.lambda_handler
      Policies:
       - Version: '2012-10-17' # Custom Policy Document
         Statement:
           - Effect: Allow
             Action:
               - cloudtrail:CreateTrail # For create_cloudtrail
               - cloudtrail:StartLogging # For create_cloudtrail
               - ec2:CreateFlowLogs
               - ec2:CreateTags
               - ec2:DeleteSecurityGroup
               - ec2:DescribeSecurityGroups
               - ec2:MonitorInstances # For ec2_enable_detailed_monitoring
               - ec2:RevokeSecurityGroupEgress
               - ec2:RevokeSecurityGroupIngress
               - ec2:StopInstances
               - ec2:TerminateInstances
               - iam:AttachRolePolicy
               - iam:AttachUserPolicy
               - iam:CreatePolicy
               - iam:CreateRole
               - iam:GetPolicy
               - iam:UpdateAccountPasswordPolicy # For IAM_turn_on_password_policy
               - s3:CreateBucket # For create_cloudtrail                              
               - s3:DeleteBucket
               - s3:DeleteBucketPolicy
               - s3:GetBucketAcl
               - s3:GetBucketPolicy
               - s3:GetObject
               - s3:PutBucketAcl
               - s3:PutBucketPolicy # For create_cloudtrail
               - s3:PutObject # For create_cloudtrail
               - sns:Publish # For exporting logs
               - sts:AssumeRole # For multi-account support
               - sts:GetCallerIdentity # For verifying what account we're running in
             Resource: '*'
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref OutputTopic
      Events:
        d9Findings:
          Type: SNS
          Properties:
            Topic: !Ref InputTopic
Outputs:
  InputTopicARN:
    Description: 'ARN that Dome9 sends events to'
    Value: !Ref InputTopic
  OutputTopicARN:
    Description: 'ARN for the export logs topic'
    Value: !Ref OutputTopic


